stages:
  - build
  - test
  - cleanup

build-job:
  tags:
    - windows-docker
  stage: build
  services: []
  script:
    - docker-compose build || exit 1
    - docker-compose up -d || exit 1

unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - pytest  # Run unit tests

cleanup-job:
  stage: cleanup
  script:
    - docker-compose down  # Tear down the services
