stages:
  - build
  - test
  - cleanup

build-job:
  tags:
    - windows-shell-true
  stage: build
  script:
    - cd ../
    - docker-compose build || exit 1
    - docker-compose up -d || exit 1

unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - pytest  
cleanup-job:
  stage: cleanup
  script:
    - docker-compose down 
