stages:
  - build
  - test
  - cleanup

build-job:
  tags:
    - windows-docker
  stage: build
  image: docker:latest
  services:
    - docker:20.10.7-dind  # Version mise à jour de Docker-in-Docker# Docker in Docker (nécessaire pour exécuter des commandes Docker dans des pipelines)
  script:
    - docker compose build || exit 1
    - docker compose up -d || exit 1

unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - pytest

cleanup-job:
  stage: cleanup
  script:
    - docker compose down