stages:
  - build
  - test
  - cleanup

build-job:
  tags:
    - windows-docker
  stage: build
  image: docker:latest  # Utilisation de l'image Docker standard
  services: []
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock  # Partage du socket Docker de l'hôte
  script:
    # Build de l'image avec docker-compose
    - docker-compose build || exit 1
    # Lancement des services en arrière-plan
    - docker-compose up -d || exit 1

unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - pytest  # Exécution des tests unitaires

cleanup-job:
  stage: cleanup
  script:
    - docker-compose down  # Arrêt des services Docker
