stages:
  - build
  - test
  - cleanup

build-job:
  stage: build
  script:
    # Construire l'image Docker sans cache
    - docker-compose build --no-cache
    - if [ $? -ne 0 ]; then exit 1; fi

    # Démarrer les services en mode détaché
    - docker-compose up -d
    - if [ $? -ne 0 ]; then exit 1; fi


unit-test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - docker ps
    - docker exec esi-projet-fil-rouge-api-1 pytest
cleanup-job:
  tags:
  - windows-shell-true
  stage: cleanup
  script:
    - docker-compose down 
