stages:          # List of stages for jobs, and their order of execution
  - build
  - test


build-job:
  tags:
    - windows-docker       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker compose build || exit 1
    - docker compose up -d || exit 1

unit-test-job:
  tags:
  - windows-docker    
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - pytest
  