# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medisecure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./medisecure-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/medisecure
      - JWT_SECRET_KEY=your_secret_key_here
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./medisecure-backend:/app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  web:
    build: ./medisecure-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./medisecure-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - api

  k6:
    image: loadimpact/k6  # Utilise l'image officielle de k6 si tu veux exécuter des tests de charge
    depends_on:
      - api
    networks:
      - default

   

volumes:
  postgres_data: